### PR TITLE
Fix mvn creds not updating

### PR DESCRIPTION
**Pull request by ibolton336**
https://issues.redhat.com/browse/TACKLE-514

### CODE REVIEW

**Review by gildub — CHANGES_REQUESTED** [review]
In the application expanded area the credentials is not showing up when maven credentials are added to an application.

**Comment by ibolton336** [comment]
> In the application expanded area the credentials is not showing up when maven credentials are added to an application.

Sounds like a separate issue.

**Comment by gildub** [comment]
Oh I might be wrong meanwhile the related issue says "Maven creds not displayed upon expanding an application"

**Comment by ibolton336** [comment]
> Oh I might be wrong meanwhile the related issue (Tackle-514) says "Maven creds not displayed upon expanding an application"

The screenshot seems to suggest it is with the "expanded" edit credentials modal.

**Review by gildub — APPROVED** [review]
LGTM

**Pull request merged**
