### PR TITLE
TACKLE-417: Change style of perspective selector to match PatternFly design guidelines

### PR DESCRIPTION
**Pull request by mturley**
Resolves https://issues.redhat.com/browse/TACKLE-417

After discussion in Slack we determined that the design of the perspective selector should match the design guidelines found here: https://www.patternfly.org/v4/components/context-selector/design-guidelines#recommended-placement-0

Reference design:

image (21)

It appears that the PF React components and CSS are not currently aligned with this design, so I've gotten as close as possible to this design in the meantime with custom CSS. I used as many PF CSS variables as possible so colors will stay up to date if these colors change in future versions. We may want to revisit this if the components change in PatternFly later on.

New screenshots:
Screen Shot 2022-05-19 at 1 13 14 PM
Screen Shot 2022-05-19 at 1 13 20 PM

### CODE REVIEW

**Comment by mturley** [comment]
@rromannissen how do you feel about this implementation?

**Review by jortel — CHANGES_REQUESTED** [review]
Issue re-aligned to 2.0.1 by PM.
Leave open and we'll merge for 2.0.1.

**Comment by mturley** [comment]
I'll convert to a draft PR so we don't accidentally merge.

**Review by jortel — COMMENTED** [review]
Approved by Ramon.

**Comment by mturley** [comment]
@ibolton336 @gildub this is ready to go if one of you has time to review.

**Review by gildub — APPROVED** [review]
LGTM

**Pull request merged**
