### PR TITLE
:bug: Upgrade `express` dependency

### PR DESCRIPTION
**Pull request by sjd78**
Resolves: https://issues.redhat.com/browse/MTA-2934

Upgrade the `express` dependency in the server workspace to resolve security issues.

### CODE REVIEW

**Review by rayfordj — CHANGES_REQUESTED** [review]
We're still pulling in 4.18.2 as a dependency with this change.

```
$ curl -s 'https://cachito.engineering.redhat.com/api/v1/requests/1559257' | jq -r '.packages[].dependencies[]| select(.name == "express")'
{
  "dev": false,
  "name": "express",
  "replaces": null,
  "type": "npm",
  "version": "4.18.2"
}
{
  "dev": false,
  "name": "express",
  "replaces": null,
  "type": "npm",
  "version": "4.19.2"
}
```

**Review by rayfordj — APPROVED** [review]
/lgtm 

Successful downstream scratch build with this change.

```
$ curl -s 'https://cachito.engineering.redhat.com/api/v1/requests/1559286' | jq -r '.packages[].dependencies[]| select(.name == "express")'
{
  "dev": false,
  "name": "express",
  "replaces": null,
  "type": "npm",
  "version": "4.19.2"
}
{
  "dev": true,  # <-- devDependency, no concerns
  "name": "express",
  "replaces": null,
  "type": "npm",
  "version": "4.18.2"
}
```

**Comment by sjd78** [comment]
Note to self: This PR needs to be manually backported to release-0.2 since the cherry-pick bot doesn't go back that far.

**Review by rayfordj — APPROVED** [review]
Even better :sunglasses: 
Thanks, @sjd78 !

/lgtm

```
$ curl -s 'https://cachito.engineering.redhat.com/api/v1/requests/1559440' | jq -r '.packages[].dependencies[]| select(.name == "express")'
{
  "dev": false,
  "name": "express",
  "replaces": null,
  "type": "npm",
  "version": "4.19.2"
}

```

**Pull request merged**
