### PR TITLE
:bug:  Capitalize first letter of tag source

### PR DESCRIPTION
**Pull request by rszwajko**
Resolves: https://issues.redhat.com/browse/MTA-2287

### CODE REVIEW

**Comment by rszwajko** [comment]
Depends on: #1802

**Comment by rszwajko** [comment]
### Before
Screenshot from 2024-04-02 15-14-08

### After

Screenshot from 2024-04-02 15-10-41

**Review by ibolton336 — APPROVED** [review]
LGTM

**Review by sjd78 — APPROVED** [review]
LGTM

**Comment by sjd78** [comment]
FWIW - the cherry-pick bot failed on 1802 (https://github.com/konveyor/tackle2-ui/actions/runs/8599628022/job/23562934915#step:4:31).  That PR probably needs a manual backport before this PR is merged so the bot can create the cherry-pick automatically.

/ping @ibolton336 , @rszwajko

**Comment by ibolton336** [comment]
BP PR opened @sjd78 https://github.com/konveyor/tackle2-ui/pull/1833

**Pull request merged**
