### PR TITLE
Use React.FC vs React.FunctionComponent

### PR DESCRIPTION
**Pull request by gildub**
React.FC is actually an alias for React.FunctionComponent.
So either one can be used meanwhile let's be consistent.
This patch sets FC everywhere.

Signed-off-by: Gilles Dubreuil <gilles@redhat.com>

### CODE REVIEW

**Review by mturley — APPROVED** [review]
Sounds good to me. @ibolton336 ?

**Comment by ibolton336** [comment]
Sounds good

**Comment by ibolton336** [comment]
> Sounds good to me. @ibolton336 ?

Thoughts on https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13 ?

**Comment by mturley** [comment]
That's interesting. It sounds like that article is advocating for using neither `React.FC` or `React.FunctionComponent` and instead just having functions with the prop types annotated on the argument only?

I get the point about children I suppose. Seems weird to have an unused prop (I usually put `children: React.ReactNode` in the prop types if I'm going to use children anyway). The point about compound components makes sense if you plan to use compound components like that, but that pattern has always felt weird to me.

Seems like not a huge deal either way. If you want to switch to inline prop types and ditch `React.FC` I'd be fine with that, but I don't think it gains us much.

**Comment by mturley** [comment]
Oh, ha, look in the comments:
> As of react 18.0 there are no children in React.FC. Thus implict children is not relevant anymore

**Pull request merged**
