### PR TITLE
:bug: Disabling useFetchCache query if RWX_SUPPORTED=false

### PR DESCRIPTION
**Pull request by mguetta1**
Resolves: https://issues.redhat.com/browse/MTA-3699

### CODE REVIEW

**Review by sjd78 — COMMENTED** [review]
@mguetta1 - Can you provide some context for this change?  Is there an issue or ticket for this?  At face value it looks ok, but I'm not sure how the `isRWXSupported` flag is meant to interact with the loading spinner.

**Comment by mguetta1** [comment]
> @mguetta1 - Can you provide some context for this change? Is there an issue or ticket for this? At face value it looks ok, but I'm not sure how the `isRWXSupported` flag is meant to interact with the loading spinner.

Hi @sjd78, @dymurray 
I just opened a Jira ticket for this issue: https://issues.redhat.com/browse/MTA-3699

**Review by rszwajko — CHANGES_REQUESTED** [review]
The loading state seems the consequence of the query being active.  IMHO if the entire feature is disabled we should disable the query as well.
React query uses `enable`  flag [for this purpose](https://tanstack.com/query/v4/docs/framework/react/guides/disabling-queries).  We use in several places i.e. [here](https://github.com/konveyor/tackle2-ui/blob/f389539cb2c6ec7720dad107227dc9edcbd77ca7/client/src/app/queries/tasks.ts#L240).

**Comment by mguetta1** [comment]
> The loading state seems the consequence of the query being active. IMHO if the entire feature is disabled we should disable the query as well. React query uses `enable` flag [for this purpose](https://tanstack.com/query/v4/docs/framework/react/guides/disabling-queries). We use in several places i.e. [here](https://github.com/konveyor/tackle2-ui/blob/f389539cb2c6ec7720dad107227dc9edcbd77ca7/client/src/app/queries/tasks.ts#L240).

Done in https://github.com/konveyor/tackle2-ui/pull/1963/commits/ee7c7a2220ea4d626a90c807daf443c33a95cff3
@rszwajko better to pass `isRWXSupported` as an argument? I saw that `useFetchCache` is used only in `client/src/app/pages/repositories/Mvn.tsx`

**Review by rszwajko — APPROVED** [review]
LGTM! If there will be another use case for  `useFetchCache` then we can always refactor.

**Comment by rszwajko** [comment]
@mguetta1 please edit the title to better reflect the fix.

**Pull request merged**
