### PR TITLE
:sparkles: Update stakeholders table to use ActionsColumn

### PR DESCRIPTION
**Pull request by mguetta1**
Part of https://github.com/konveyor/tackle2-ui/issues/1318

image

UI Tests PR: 1201

### CODE REVIEW

**Comment by sjd78** [comment]
Part of #1318?

**Review by sjd78 — COMMENTED** [review]
Looks like a good change.  @mguetta1 any reason it is still in draft?

**Comment by mguetta1** [comment]
> Part of #1318?

Yes

**Comment by mguetta1** [comment]
> Looks like a good change. @mguetta1 any reason it is still in draft?

I need to change this to use https://github.com/konveyor/tackle2-ui/blob/main/client/src/app/pages/controls/ControlTableActionButtons.tsx

**Review by sjd78 — APPROVED** [review]
LGTM

**Comment by sjd78** [comment]
@mguetta1 The PR change is causing e2e-ui-test fails:
  - https://github.com/konveyor/tackle2-ui/actions/runs/10710591872/job/29700435669#step:12:1176
  - https://github.com/konveyor/tackle2-ui/actions/runs/10710591872/job/29700435669#step:12:2307

The test is probably looking for a kebab menu action that doesn't exists or got moved to the edit pencil.

**Comment by mguetta1** [comment]
> @mguetta1 The PR change is causing e2e-ui-test fails:
> 
> * https://github.com/konveyor/tackle2-ui/actions/runs/10710591872/job/29700435669#step:12:1176
> * https://github.com/konveyor/tackle2-ui/actions/runs/10710591872/job/29700435669#step:12:2307
> 
> The test is probably looking for a kebab menu action that doesn't exists or got moved to the edit pencil.

Correct, here is the related PR in tackle-ui-tests: https://github.com/konveyor/tackle-ui-tests/pull/1201
Please coordinate with @sshveta to merge the changes

**Comment by sjd78** [comment]
> Correct, here is the related PR in tackle-ui-tests: [konveyor/tackle-ui-tests#1201](https://github.com/konveyor/tackle-ui-tests/pull/1201) Please coordinate with @sshveta to merge the changes

We can tell CI to use that PR in the e2e testing: https://github.com/konveyor/ci?tab=readme-ov-file#referencing-specific-pull-requests-in-the-test-repositories

**Comment by sjd78** [comment]
Note: Closed and reopened the PR to force all the check to run again with the update to the PR description to use a UI tests PR for e2e-ui testing.

**Comment by sjd78** [comment]
@mguetta1 - One more UI test fix needed for: https://github.com/konveyor/tackle2-ui/actions/runs/10722793005/job/29734751734?pr=1923#step:12:1174

**Comment by mguetta1** [comment]
> @mguetta1 - One more UI test fix needed for: https://github.com/konveyor/tackle2-ui/actions/runs/10722793005/job/29734751734?pr=1923#step:12:1174
> 
> Looks like a migration wave test that is setting up stakeholders first.

Thanks @sjd78. Fixed in 2feda3c3997db527d7ce1ddf8a2cf55bd88c5e1e

**Pull request merged**
