### PR TITLE
:bug: Fix broken analysis report download

### PR DESCRIPTION
**Pull request by ibolton336**
- Revert part of  https://github.com/konveyor/tackle2-ui/commit/1117014e7943f75037d9543a0d4966965207e96d#diff-31cbe8bc7269f3b48ffa72c630c1eaab5355bcca48361242ce31fc18543a8afa which broke the analysis report download functionality 

Resolves https://issues.redhat.com/browse/MTA-1369
Resolves https://issues.redhat.com/browse/MTA-1386

### CODE REVIEW

**Comment by pranavgaikwad** [comment]
seems to have fixed the download issue: 

Peek 2023-09-27 13-15

**Comment by ibolton336** [comment]
Closes https://issues.redhat.com/browse/MTA-393

**Review by sjd78 — CHANGES_REQUESTED** [review]
When I test this PR rebased on current main, the download button fails for both report types.  I can try rebuilding my operator and test again tomorrow.

**Review by sjd78 — APPROVED** [review]
Testing with a fresh install of the operator and the download links are working for both the tar and the yaml files.

**Pull request merged**
