### PR TITLE
:sparkles: Regroup the dependencies table on name only, version/sha shown in details

### PR DESCRIPTION
**Pull request by sjd78**
Resolves: #1338
Resolves: https://issues.redhat.com/browse/MTA-1585

Depends on hub change https://github.com/konveyor/tackle2-hub/issues/557 / https://github.com/konveyor/tackle2-hub/pull/558.

Summary of changes:
  - The dependency table will show a single row for every named dependency.
  - Multiple versions will be aggregated as a single row.
  - Details about multiple versions will be available in the details drawer.
  - The details view application table will show the application + version, allowing for all versions used to be listed.

Screencap:

https://github.com/konveyor/tackle2-ui/assets/3985964/6d57aa6e-ce8a-4e2f-9a6f-ebedd79e2241

### CODE REVIEW

**Review by ibolton336 — APPROVED** [review]

**Comment by sjd78** [comment]
**PROBLEM**: The dependency data being returned will have a record for each dependency name+sha combo.  Therefore, additional changes need to be made so the sha/version is only dealt with in the dependency drawer.  Without a change, if multiple versions of a dependency exist, it will be shown with 2 identical looking rows.

**Comment by sjd78** [comment]
> **PROBLEM**: The dependency data being returned will have a record for each dependency name+sha combo. Therefore, additional changes need to be made so the sha/version is only dealt with in the dependency drawer. Without a change, if multiple versions of a dependency exist, it will be shown with 2 identical looking rows.

This is resolved with https://github.com/konveyor/tackle2-hub/issues/557 and changes to the data/UI flow.

**Comment by ibolton336** [comment]
This also resolves https://issues.redhat.com/browse/MTA-1585

**Comment by sjd78** [comment]
Merging blocked waiting on hub for https://github.com/konveyor/tackle2-hub/pull/558

**Pull request merged**
