### PR TITLE
:sparkles: Jira: Add URL filter and sorting

### PR DESCRIPTION
**Pull request by gildub**
Resolves https://issues.redhat.com/browse/MTA-908

### CODE REVIEW

**Review by ibolton336 — APPROVED** [review]

**Comment by sjd78** [comment]
@gildub, @ibolton336 - Does this actually solve MTA-908 that states "Incorrect sorting by URL for Jira instances"?

A quick look at the table component and I saw:
https://github.com/konveyor/tackle2-ui/blob/54f156bbdec2a8e25ae9e5a80f68f7bf4d95b147/client/src/app/pages/external/jira/trackers.tsx#L126-L129

I'm assuming that TODO item is the cause of MTA-908.

**Comment by ibolton336** [comment]
Ahh good catch @sjd78 - I tested that this filter was working but missed that the linked issue is actually dealing with sort.

**Review by ibolton336 — APPROVED** [review]
Could you add the sort support here too per @sjd78's suggestion?

**Review by ibolton336 — CHANGES_REQUESTED** [review]

**Comment by gildub** [comment]
@sjd78, yeah I missed that too. Thanks.

**Review by sjd78 — APPROVED** [review]
LGTM

**Review by ibolton336 — APPROVED** [review]

**Pull request merged**
