### PR TITLE
:seedling: 1236 - changes to StatusIcon (now IconedStatus)

### LINKED ISSUE #1236: Remove StatusIcon component
Conversation in https://github.com/konveyor/tackle2-ui/issues/1070 and about it in slack have determined that Patternfly improvements have made this component unnecessary.

### PR DESCRIPTION
**Pull request by gitdallas**
closes #1236

### CODE REVIEW

**Comment by gitdallas** [comment]
ended up just adding "presets" which work similarly to what was previously "label", but that value is more of a preset to me as it includes status+label+icon.

overridable as you can now also supply your own status/label/icon and it will override anything in the preset if you used one.

**Comment by gitdallas** [comment]
I'm not sure why a bunch of the snaps changed after i rebased with main

**Comment by sjd78** [comment]
> I'm not sure why a bunch of the snaps changed after i rebased with main - they added `Object` locally, but the ci isn't... like some sort of config changed

See #1247 

Essentially I upgraded Jest to version 29 and the snapshot format changed.  Rebase on main (a proper `git rebase upstream/main` assuming you name your git remote to this repo as upstream), do a new `npm install` to upgrade your stuff, then run again.

**Review by sjd78 — COMMENTED** [review]
The component changes look ok to me.  I don't mind the s/label/preset/ rename.

Let just make sure the component rename is approved by more than me!

Finally, getting all of the snapshot updates not related to the PR itself out of the PR would be good.

**Review by sjd78 — APPROVED** [review]
LGTM.

@ibolton336 , @gildub - Good with the new name?

**Comment by ibolton336** [comment]
> LGTM.
> 
> @ibolton336 , @gildub - Good with the new name?

I don't love the name hah. But not a big enough gripe to push back on it. LGTM

**Review by ibolton336 — APPROVED** [review]

**Pull request merged**
