### PR TITLE
:seedling: Upgrade to Patternfly 5.2

### PR DESCRIPTION
**Pull request by sjd78**
Update to the latest 5.2.x releases of the patternfly libraries.

Changed the dependency version to specific pinned versions to be extra clear that we test and verify against exactly the versions in the `package.json`.

See release notes https://www.patternfly.org/get-started/release-highlights/#patternfly-5.2

### CODE REVIEW

**Comment by sjd78** [comment]
I have no idea why e2e-ui CI is failing here:
Migration Waves CRUD operations -- Migration Wave CRUD (failed)

Running locally the date selector looks and works correctly.

**Comment by ibolton336** [comment]
> I have no idea why e2e-ui CI is failing here: Migration Waves CRUD operations -- Migration Wave CRUD (failed)
> 
> Running locally the date selector looks and works correctly.

Not sure - maybe a network timeout anomaly?

**Comment by ibolton336** [comment]
@sjd78 Looks like the fix made it to 5.2.3

https://github.com/patternfly/patternfly-react/releases/tag/5.2.3

**Review by ibolton336 — APPROVED** [review]
LGTM!

**Comment by sjd78** [comment]
Need to have https://github.com/konveyor/tackle-ui-tests/pull/1069 merged before merging this PR.

**Review by ibolton336 — APPROVED** [review]

**Review by rszwajko — APPROVED** [review]

**Pull request merged**
